
name: Build & Push Frontend to ECR

on:
  push:
    branches:
      - front

jobs:
  build:
    name: Build Frontend Image & push to ECR
    runs-on: ubuntu-latest


    steps:
    
    # Étape 1 : Checkout le code source du dépôt
    - name: Checkout code
      uses: actions/checkout@v3

    # Étape 2 : Configurer les identifiants AWS
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ secrets.AWS_REGION }}
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    # Étape 3 : Connexion à Amazon ECR
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    # Étape 4 : Construire, taguer et pousser l'image vers ECR
    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: front-app  # NOM DU REPO ECR POUR LE FRONTEND
        IMAGE_TAG: latest
      run: |
        # Construire l'image Docker (ajouter "-f frontend/Dockerfile" si nécessaire)
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }} -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        
        # Pousser l'image dans ECR
        docker push $ECR_REGISTRY/$ECR_REPOSITORY --all-tags